# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-disksize"
  # Definir la primera máquina virtual (Ubuntu) como 'test'
  config.vm.define "test" do |vmtest|
    vmtest.vm.box = "ubuntu/jammy64"
    vmtest.vm.hostname = "test"
    #vmtest.vm.network "private_network", type: "static", ip: "192.168.56.4"
    vmtest.vm.network "private_network", :name => '', ip: "192.168.56.4"
    vmtest.vm.boot_timeout = 1800  # Aumentar el tiempo de espera a 30 minutos

    # Discos adicionales
    vmtest.vm.disk :disk, size: "5GB", name: "DISK1"
    vmtest.vm.disk :disk, size: "3GB", name: "DISK2"
    vmtest.vm.disk :disk, size: "2GB", name: "DISK3"
    vmtest.vm.disk :disk, size: "1GB", name: "DISK4_EXTRA"

    # Comparto la carpeta del host donde estoy parado contra la VM
    vmtest.vm.synced_folder 'compartido_test/', '/home/vagrant/compartido',
    owner: 'vagrant', group: 'vagrant'

    # Configuración del proveedor VirtualBox
    vmtest.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "test"
      vb.cpus = 1
      vb.linked_clone = true
    end

    # Provisión para la máquina Ubuntu
    vmtest.vm.provision "shell", path: "provision.sh"
    vmtest.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmtest.vm.provision "shell", path: "users.sh"
    vmtest.vm.provision "shell", privileged: false, inline: <<-SHELL
    mkdir -p /home/vagrant/repogit
    cd /home/vagrant/repogit
    git clone https://github.com/upszot/UTN-FRA_SO_TP-Integral.git

    SHELL
  end

  # Definir la segunda máquina virtual (Fedora) como 'prod'
  config.vm.define "prod" do |vmprod|
    vmprod.vm.box = "generic/fedora36"
    vmprod.vm.hostname = "prod"
    #vmprod.vm.network "private_network", type: "static", ip: "192.168.56.5"
    vmprod.vm.network "private_network", :name => '', ip: "192.168.56.5"
    vmprod.vm.boot_timeout = 1800  # Aumentar el tiempo de espera a 30 minutos

    # Discos adicionales
    vmprod.vm.disk :disk, size: "5GB", name: "DISK1"
    vmprod.vm.disk :disk, size: "3GB", name: "DISK2"
    vmprod.vm.disk :disk, size: "2GB", name: "DISK3"
    vmprod.vm.disk :disk, size: "1GB", name: "DISK4_EXTRA"

    # Comparto la carpeta del host donde estoy parado contra la VM
    vmprod.vm.synced_folder 'compartido_prod/', '/home/vagrant/compartido',
    owner: 'vagrant', group: 'vagrant'

    # Configuración del proveedor VirtualBox
    vmprod.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "prod"
      vb.cpus = 1
      vb.linked_clone = true
    end

    # Provisión para la máquina Fedora
    vmprod.vm.provision "shell", path: "provision.sh"
    vmprod.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmprod.vm.provision "shell", path: "users.sh"
  end

end
